### PR TITLE
attempt to bring ember-data

### PR DESCRIPTION
**Pull request by lifeart**
Resolves: https://github.com/lifeart/demo-ember-vite/issues/16

In short, we able to fix main breakage using following steps:
* override ember-data-private-build-infra
* patching `getOwnConfig`
* configuring vite to `optimizeDeps.exclude: ['@ember-data/store']` (loosing symbols)
* adding `@babel/plugin-transform-typescript` to build not-builded e-data deps

### CODE REVIEW

**Comment by lifeart** [comment]
tldr: error `simplified` to 
image

**Comment by lifeart** [comment]
V2 addons should be helpful here, linking: https://github.com/emberjs/data/issues/8103

**Comment by runspired** [comment]
we're close to being able to ship v2 addons, only 2 bugs left in embroider for us to be able to do so.

**Comment by lifeart** [comment]
@runspired sorry to bothering you here, is it possible (in theory), to get ember-data working at this point (without embroider)?

**Comment by lifeart** [comment]
Looks like we have prod build issues here (netlify preview)
image
image

**Pull request merged**
