### PR TITLE
Add ember-intl

### PR DESCRIPTION
**Pull request by kaermorchen**
#25

### CODE REVIEW

**Comment by kaermorchen** [comment]
It use json file instead of yaml

**Comment by kaermorchen** [comment]
@lifeart Don't merge, I will add yaml support

**Comment by lifeart** [comment]
@kaermorchen could you rebase plz, I just pushed my ember-intl sample, I like your idea on async json loading!

**Comment by kaermorchen** [comment]
YAML support is added.

**Comment by lifeart** [comment]
@kaermorchen thank you for contribution!

**Pull request merged**
