### PR TITLE
glint (not working)

### PR DESCRIPTION
**Pull request by lifeart**
Ref: https://typed-ember.gitbook.io/glint/using-glint/ember/installation

Related to https://github.com/lifeart/demo-ember-vite/issues/17

Have no idea why glint is not responding..

### CODE REVIEW

**Comment by kaermorchen** [comment]
I haven't worked with glint. I see errors in console and vscode. 

What did you mean in "not responding"?

**Comment by lifeart** [comment]
@kaermorchen glint language server extension does not emit anything https://marketplace.visualstudio.com/items?itemName=typed-ember.glint-vscode (in output console). Just silence. Require some debugging :)

**Comment by kaermorchen** [comment]
@lifeart I have done a lite investigation. Glint is working but expect ember application file structures (in not all cases).

For example, if I rename button component:
`components/Button/index.ts` => `components/button.ts` 
`components/Button/template.hbs` => `components/button.hbs` 

Glint will see the signature and show the errors in console output.

I have tried add signature for the helper `memory-usage` and it works too.

**Comment by kaermorchen** [comment]
Glint declaration works too
```ts
declare module '@glint/environment-ember-loose/registry' {
  export default interface Registry {
    'memory-usage': typeof MemoryUsage;
  }
}
```

Untitled

**Comment by lifeart** [comment]
Now it's working, registry transformed to type registry

**Pull request merged**
